#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; IMAGE="dokku/$APP"; REVISION_FILE="$DOKKU_ROOT/$APP/.dokku-revision"

dokku_log_info1 "Preparing revision information..."

if [[ ! -d "$DOKKU_ROOT/$APP/refs" ]]; then
  dokku_log_warn "Not a git repository"
  exit 0
fi

cd "$DOKKU_ROOT/$APP/"
cat > .dokku-revision <<EOL
export REVISION_INFO=true
export REVISION_BRANCH='$(git branch | sed -n "/^\*/s/^\* //p")'
export REVISION_AUTHOR='$(git log -1 --format="%an")'
export REVISION_HASH='$(git rev-parse --short HEAD)'
export REVISION_DATE='$(git log -1 --format="%ci")'
export REVISION_BUILD_DATE='$(date "+%F %H:%M:%S %z")'
EOL

dokku_log_verbose "Complete"

dokku_log_info1 "Saving revision information..."

REVISION_INFO=$(cat "$REVISION_FILE")
rm "$REVISION_FILE"

id=$(echo "$REVISION_INFO" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.profile.d/revision-info.sh")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

dokku_log_verbose "Complete"
