#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"; IMAGE="dokku/$APP"; REVISION_FILE="$DOKKU_ROOT/$APP/.dokku-revision"

[[ ! -f "$REVISION_FILE" ]] && exit 0

REVISION_INFO=$(cat "$REVISION_FILE")
rm "$REVISION_FILE"

dokku_log_info1 "Saving revision information..."

id=$(echo "$REVISION_INFO" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.profile.d/revision-info.sh")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

dokku_log_verbose "Complete"
