#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"

[[ ! -d "$DOKKU_ROOT/$APP/refs" ]] && exit 0

dokku_log_info1 "Preparing revision information..."

cd "$DOKKU_ROOT/$APP/"
cat > .dokku-revision <<EOL
export REVISION_INFO=true
export REVISION_BRANCH='$(git branch | sed -n "/^\*/s/^\* //p")'
export REVISION_AUTHOR='$(git log -1 --format="%an")'
export REVISION_HASH='$(git rev-parse --short HEAD)'
export REVISION_DATE='$(git log -1 --format="%ci")'
export REVISION_BUILD_DATE='$(date "+%F %H:%M:%S %z")'
EOL

dokku_log_verbose "Complete"
